# Generated by Django 4.2.7 on 2025-09-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("up_engage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="qa_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether Q&A is enabled for this event"
            ),
        ),
    ]
